In [1]:
import numpy as np

In [2]:
# Player IDs (10 players)
players = np.arange(1, 11)
#random points scored in 5 games (10 players × 5 games)
points = np.random.randint(0, 30, size=(10,5))

In [3]:
print("Players:", players)
print("Points:\n", points)
print("Shape : ", points.shape, "Size : ", points.size, "Dtype:", points.dtype)

Players: [ 1  2  3  4  5  6  7  8  9 10]
Points:
 [[14 18 21  1 28]
 [ 8 23  6  2 13]
 [29 20  5 15 14]
 [ 1 18  8 20 21]
 [26 13  2  6  5]
 [ 5  0  1 26 17]
 [27  4 19 11 15]
 [ 8 26 15 22 12]
 [ 3 23 15  8 24]
 [ 9 10 15 15 21]]
Shape :  (10, 5) Size :  50 Dtype: int32


In [4]:
print("Points of player 1:", points[0])
print("Points in game 3 (all players):", points[:, 2])
print("Points of players 1–3 in games 2–4:\n", points[0:3, 1:4])

Points of player 1: [14 18 21  1 28]
Points in game 3 (all players): [21  6  5  8  2  1 19 15 15 15]
Points of players 1–3 in games 2–4:
 [[18 21  1]
 [23  6  2]
 [20  5 15]]


In [5]:
## Broadcasting
bonus = 2
points_bonus = points + bonus
points_bonus

array([[16, 20, 23,  3, 30],
       [10, 25,  8,  4, 15],
       [31, 22,  7, 17, 16],
       [ 3, 20, 10, 22, 23],
       [28, 15,  4,  8,  7],
       [ 7,  2,  3, 28, 19],
       [29,  6, 21, 13, 17],
       [10, 28, 17, 24, 14],
       [ 5, 25, 17, 10, 26],
       [11, 12, 17, 17, 23]], dtype=int32)

In [6]:
## Vectorized Operation

weights = np.array([1, 1.2, 1, 1.5, 1])
weighted_points = points*weights
weighted_points

array([[14. , 21.6, 21. ,  1.5, 28. ],
       [ 8. , 27.6,  6. ,  3. , 13. ],
       [29. , 24. ,  5. , 22.5, 14. ],
       [ 1. , 21.6,  8. , 30. , 21. ],
       [26. , 15.6,  2. ,  9. ,  5. ],
       [ 5. ,  0. ,  1. , 39. , 17. ],
       [27. ,  4.8, 19. , 16.5, 15. ],
       [ 8. , 31.2, 15. , 33. , 12. ],
       [ 3. , 27.6, 15. , 12. , 24. ],
       [ 9. , 12. , 15. , 22.5, 21. ]])

In [7]:
## Aggregation - 

print("Total points by each player:", points.sum(axis=1))
print("Average points per game:", points.mean(axis=0))
print("Overall max score:", points.max())

Total points by each player: [82 52 83 68 52 49 76 83 73 70]
Average points per game: [13.  15.5 10.7 12.6 17. ]
Overall max score: 29


In [8]:
## Boolean masking and filtering
print("Players who scored > 100 total : ", players[points.sum(axis=1)>100])
print("Game 1 scores > 20 : ", points[points[:, 0]>20, 0])

Players who scored > 100 total :  []
Game 1 scores > 20 :  [29 26 27]


In [9]:
## Reshaping and stacking - 
flat = points.flatten()
print("Flattened : ", flat[:15])

# reshaped = points.reshape(5, 10)
# reshaped

points_team2 = np.random.randint(0, 30, size=(10,5))
combined = np.vstack([points, points_team2])
print("Combined shape : ", combined.shape)
combined

Flattened :  [14 18 21  1 28  8 23  6  2 13 29 20  5 15 14]
Combined shape :  (20, 5)


array([[14, 18, 21,  1, 28],
       [ 8, 23,  6,  2, 13],
       [29, 20,  5, 15, 14],
       [ 1, 18,  8, 20, 21],
       [26, 13,  2,  6,  5],
       [ 5,  0,  1, 26, 17],
       [27,  4, 19, 11, 15],
       [ 8, 26, 15, 22, 12],
       [ 3, 23, 15,  8, 24],
       [ 9, 10, 15, 15, 21],
       [ 7,  0,  9, 11,  6],
       [10,  2, 15,  2,  5],
       [ 0, 14, 26, 10, 16],
       [12,  0,  4, 25, 22],
       [20, 17, 15, 22,  9],
       [ 5, 26,  0, 18,  4],
       [10,  4,  8,  6,  9],
       [22, 29, 25,  7, 18],
       [17, 26,  2,  5,  6],
       [ 7, 21,  9,  1, 23]], dtype=int32)

In [10]:
## Liner algebra - 

corr = np.corrcoef(points)
print("Corelation shape : ", corr.shape)
corr

Corelation shape :  (10, 10)


array([[ 1.        ,  0.51032048, -0.23622351, -0.00342932, -0.1735662 ,
        -0.46521366,  0.09737038, -0.36823551,  0.69002905,  0.39558445],
       [ 0.51032048,  1.        ,  0.24913052,  0.26846666,  0.17775493,
        -0.52180816, -0.5437601 ,  0.37454607,  0.71366695, -0.2128793 ],
       [-0.23622351,  0.24913052,  1.        , -0.34440834,  0.94947552,
        -0.08907546,  0.23569291, -0.20468831, -0.41437409, -0.63441015],
       [-0.00342932,  0.26846666, -0.34440834,  1.        , -0.61427883,
         0.56630982, -0.82267145,  0.62119745,  0.64899997,  0.58484381],
       [-0.1735662 ,  0.17775493,  0.94947552, -0.61427883,  1.        ,
        -0.31455342,  0.43078119, -0.33774192, -0.52205348, -0.7542061 ],
       [-0.46521366, -0.52180816, -0.08907546,  0.56630982, -0.31455342,
         1.        , -0.12790041,  0.0530843 , -0.16722078,  0.55816939],
       [ 0.09737038, -0.5437601 ,  0.23569291, -0.82267145,  0.43078119,
        -0.12790041,  1.        , -0.92827131

In [11]:
## Dot product - 
print("Player 1 weighted : ", np.dot(points[0], weights))

Player 1 weighted :  86.1


In [18]:
## Random and reproducibility - 

np.random.seed(42)
random_scores = np.random.normal(loc=15, scale=5, size=(10,5))
random_scores

array([[17.48357077, 14.30867849, 18.23844269, 22.61514928, 13.82923313],
       [13.82931522, 22.89606408, 18.83717365, 12.65262807, 17.71280022],
       [12.68291154, 12.67135123, 16.20981136,  5.43359878,  6.37541084],
       [12.18856235,  9.9358444 , 16.57123666, 10.45987962,  7.93848149],
       [22.32824384, 13.8711185 , 15.33764102,  7.87625907, 12.27808638],
       [15.55461295,  9.24503211, 16.87849009, 11.99680655, 13.54153125],
       [11.99146694, 24.26139092, 14.93251388,  9.71144536, 19.11272456],
       [ 8.89578175, 16.04431798,  5.20164938,  8.35906976, 15.98430618],
       [18.6923329 , 15.85684141, 14.42175859, 13.49448152,  7.60739005],
       [11.40077896, 12.69680615, 20.28561113, 16.71809145,  6.18479922]])